// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1XCeYEiEVRO8JWw6F_0A93QD7tC29PmU',
    appId: '1:135725594146:web:e4ee5b952a2e9fbc513c7b',
    messagingSenderId: '135725594146',
    projectId: 'cureapp-6b9f4',
    authDomain: 'cureapp-6b9f4.firebaseapp.com',
    storageBucket: 'cureapp-6b9f4.firebasestorage.app',
    measurementId: 'G-HFZLRRDVWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiucKnb7dQV6PRJOSWmgiyiitTzwuZbWo',
    appId: '1:135725594146:android:bbd788b39e979ecb513c7b',
    messagingSenderId: '135725594146',
    projectId: 'cureapp-6b9f4',
    storageBucket: 'cureapp-6b9f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3VW-scszpL0xqTrPW9qDJt0P-ogU-GgA',
    appId: '1:135725594146:ios:6df4d94985af0a35513c7b',
    messagingSenderId: '135725594146',
    projectId: 'cureapp-6b9f4',
    storageBucket: 'cureapp-6b9f4.firebasestorage.app',
    iosBundleId: 'com.example.cureApp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3VW-scszpL0xqTrPW9qDJt0P-ogU-GgA',
    appId: '1:135725594146:ios:6df4d94985af0a35513c7b',
    messagingSenderId: '135725594146',
    projectId: 'cureapp-6b9f4',
    storageBucket: 'cureapp-6b9f4.firebasestorage.app',
    iosBundleId: 'com.example.cureApp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1XCeYEiEVRO8JWw6F_0A93QD7tC29PmU',
    appId: '1:135725594146:web:2345c3055e078cbf513c7b',
    messagingSenderId: '135725594146',
    projectId: 'cureapp-6b9f4',
    authDomain: 'cureapp-6b9f4.firebaseapp.com',
    storageBucket: 'cureapp-6b9f4.firebasestorage.app',
    measurementId: 'G-P1EL5D6FV1',
  );
}
